@startuml

title Mastermind

class Mastermind {
    +play()
}

class Player {
    +proposeCombination()
    +win()
    +lose()
}

class Combination {
    +randomize()
    +compare(Combination)
    +validate()
}

class Attempt {
    +getResult()
}

class Result {
    +getSuccesses()
    +show()
}

enum Success {
    Black
    White
}

enum Color {
    Red
    Blue
    Yellow
    Green
    Orange
    Purple
}

Mastermind *--> Player
Mastermind *--> Combination : secretCombination
Player *--> "1..15" Attempt
Combination *--> "4" Color
Attempt *--> Result
Attempt *--> Combination : proposedCombination
Result *--> "0.. 4" Success

@enduml